name: "Sphinx: Render docs"

on: 
  push:
    branches:
      - 'main'
    
env:
  GIT_USER_NAME: BattINFO Developers
  GIT_USER_EMAIL: "BattINFO@big-map.org"
    
jobs:

  updatepages:
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4 #Uses python install action from here: https://github.com/marketplace?type=actions
      with:
        python-version: '3.10'  # Replace with the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Markdown==3.4.3 rdflib==6.3.2  # Add any other dependencies if needed
        
    - name: Render documentation from ttl
      run: python docs/ttl_to_rst.py

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "apt-get update -y; apt-get install -y pandoc"
        
    - name: Create context file from ttl
      run: python docs/ttl_to_context.py

    - name: Check if HTML context directory exists
      run: |
        if [ ! -d "docs/_build/html/context/" ]; then
          echo "Creating HTML context directory"
          sudo mkdir -p docs/_build/html/context/
        else
          echo "HTML context directory already exists"
        fi
    
    - name: Copy context file to HTML directory
      run: sudo cp context/context.json docs/_build/html/context/
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentationHTML
        path: docs/_build/html/
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html

      
